// src/components/CattleMap.tsx
import React, { useState } from 'react';
import { MapContainer, TileLayer, Marker, Popup, useMap } from 'react-leaflet';
import { StatsPanel } from './StatsPanel';
import { SensorChartModal } from './SensorChartModal';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';
import 'leaflet.fullscreen';
import { CattleSensorData, generateSensorData } from '../types/sensor';

interface CattleData {
  id: string;
  position: [number, number];
  healthStatus: 'healthy' | 'warning' | 'critical';
  sensorData: CattleSensorData;
}

// 全屏控制组件
const FullScreenControl = () => {
  const map = useMap();
  L.control.fullscreen().addTo(map);
  return null;
};

const CattleMap = () => {
  // 模拟牛数据
  const cattleData: CattleData[] = Array.from({ length: 50 }, (_, i) => ({
    id: (i + 1).toString(),
    position: [28.25 + Math.random() * 0.01, 112.895 + Math.random() * 0.015],
    healthStatus: Math.random() < 0.8 ? 'healthy' : (Math.random() < 0.5 ? 'warning' : 'critical'),
    sensorData: generateSensorData()
  }));

  const [selectedCattle, setSelectedCattle] = useState<CattleData | null>(null);

  // 健康状态对应颜色
  const getMarkerIcon = (status: string) => {
    switch (status) {
      case 'healthy': return '/assets/images/健康的牛.png';
      case 'warning': return '/assets/images/有风险的牛.png';
      case 'critical': return '/assets/images/不健康的牛.png';
      default: return '/assets/images/未知状态的牛.png';
    }
  };

  // 创建自定义图标
  const createCustomIcon = (iconUrl: string) => {
    const isCritical = iconUrl.includes('不健康的牛');
    return L.divIcon({
      className: 'custom-marker',
      html: `<div class="marker-container ${isCritical ? 'critical-pulse' : ''}" style="${isCritical ? 'animation: pulse 1.5s ease-in-out infinite; transform-origin: center;' : ''}">
        <img src="${iconUrl}" style="width:32px; height:32px"/>
      </div>`,
      iconSize: [32, 32],
    });
  };

  return (
    <div className="map-container" style={{ position: 'relative', height: '100%' }}>
      <StatsPanel cattleData={cattleData} />
      <MapContainer
        center={[28.2282, 112.9388]}
        zoom={12}
        style={{ height: 'calc(100vh - 64px)', minHeight: '480px', width: '100%' }}
        zoomControl={true}
      >
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='© OpenStreetMap contributors'
        />
        <FullScreenControl />
        {cattleData.map((cattle) => (
          <Marker
            key={cattle.id}
            position={cattle.position}
            icon={createCustomIcon(getMarkerIcon(cattle.healthStatus))}
            eventHandlers={{ click: () => setSelectedCattle(cattle) }}
          />
        ))}
      </MapContainer>
      {selectedCattle && <SensorChartModal data={selectedCattle.sensorData} onClose={() => setSelectedCattle(null)} />}
    </div>
  );
};

export default CattleMap;

// PC/frontend/src/app/components/cattle-map/cattle-map.component.ts
import { Component, AfterViewInit, OnDestroy, ChangeDetectorRef, PLATFORM_ID, Inject } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { CattleService } from '../../services/cattle.service';
import { Cattle } from '../../models/cattle';
import { Sensor } from '../../models/sensor';
import { LoadingSpinnerComponent } from '../loading-spinner/loading-spinner.component';
import { StatsPanelComponent } from '../stats-panel/stats-panel.component';
import { SensorChartModalComponent } from '../sensor-chart-modal/sensor-chart-modal.component';
// import * as L from 'leaflet';  

interface SelectedCattleData extends Cattle {
  sensorData: Sensor;
}

@Component({
  selector: 'app-cattle-map',
  standalone: true,
  imports: [
    CommonModule,
    LoadingSpinnerComponent,
    StatsPanelComponent,
    SensorChartModalComponent
  ],
  templateUrl: './cattle-map.component.html',
  styleUrl: './cattle-map.component.scss'
})
export class CattleMapComponent implements AfterViewInit, OnDestroy {
  cattleData: Cattle[] = [];
  selectedCattle: SelectedCattleData | null = null;
  loading = true;
  loadingSensorData = false;
  error: string | null = null;
  private map: any;
  private L: any;

  constructor(
    @Inject(PLATFORM_ID) private platformId: Object,
    private cattleService: CattleService,
    private cdr: ChangeDetectorRef
  ) {}

  ngAfterViewInit(): void {
    // 只在浏览器环境中初始化地图
    if (isPlatformBrowser(this.platformId)) {
      // 动态导入
      import('leaflet').then(leaflet => {
        this.L = leaflet;
        this.cattleService.getAllCattle().subscribe({
          next: (data) => {
            this.cattleData = data;
            this.initMap();
            this.loading = false;
            this.cdr.detectChanges();
          },
          error: (err) => {
            this.error = '无法加载牛只数据，请稍后再试';
            this.loading = false;
            this.cdr.detectChanges();
          }
        });
      });
    }
  }

  ngOnDestroy(): void {
    if (this.map) {
      this.map.remove();
    }
    
    // 移除窗口大小变化的监听
    if (isPlatformBrowser(this.platformId)) {
      window.removeEventListener('resize', () => {
        if (this.map) {
          this.map.invalidateSize();
        }
      });
    }
  }

  // 初始化地图
  private initMap(): void {
    // 创建地图实例
    this.map = this.L.map('map', {
      center: [28.2458, 112.8519],// 初始中心坐标 华宽通
      zoom: 17,
      zoomControl: true
    });

    // 添加OpenStreetMap图层
    this.L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '© OpenStreetMap contributors'
    }).addTo(this.map);

    // 添加牛只标记
    this.addCattleMarkers();

    // 确保地图尺寸正确渲染
    setTimeout(() => {
      this.map.invalidateSize();
    }, 200);

    // 添加窗口大小变化的监听
    if (isPlatformBrowser(this.platformId)) {
      window.addEventListener('resize', () => {
        if (this.map) {
          this.map.invalidateSize();
        }
      });
    }
  }

  // 添加牛只标记
  private addCattleMarkers(): void {
    this.cattleData.forEach(cattle => {
      const icon = this.createCustomIcon(cattle.healthStatus);
      const marker = this.L.marker(cattle.position as L.LatLngExpression, { icon })
        .addTo(this.map);
      
      // 添加点击事件
      marker.on('click', () => {
        this.handleSelectCattle(cattle);
      });
    });
  }

  // 健康状态对应颜色
  private getMarkerColor(status: string): string {
    switch (status) {
      case 'healthy': return '#4caf50'; // 绿色
      case 'warning': return '#ff9800'; // 橙色
      case 'critical': return '#f44336'; // 红色
      default: return '#9e9e9e'; // 灰色
    }
  }

  // 创建自定义图标
  private createCustomIcon(status: string): any {
    const color = this.getMarkerColor(status);
    const isCritical = status === 'critical';
    return this.L.divIcon({
      className: 'custom-marker',
      html: `<div class="marker-container ${isCritical ? 'critical-pulse' : ''}" style="
        width: 20px; 
        height: 20px; 
        background-color: ${color}; 
        border-radius: 50%; 
        border: 2px solid white;
        box-shadow: 0 0 4px rgba(0,0,0,0.3);
        ${isCritical ? 'animation: pulse 1.5s ease-in-out infinite; transform-origin: center;' : ''}
      "></div>`,
      iconSize: [24, 24] as L.PointExpression,
      iconAnchor: [12, 12] as L.PointExpression
    });
  }

  // 选择牛只时获取传感器数据
  handleSelectCattle(cattle: Cattle): void {
    this.loadingSensorData = true;
    this.cdr.detectChanges();
    
    this.cattleService.getCattleSensorData(cattle.id).subscribe({
      next: (sensorData) => {
        this.selectedCattle = {
          ...cattle,
          sensorData
        };
        this.loadingSensorData = false;
        this.cdr.detectChanges();
      },
      error: (err) => {
        this.error = '无法加载传感器数据，请稍后再试';
        this.loadingSensorData = false;
        this.cdr.detectChanges();
      }
    });
  }

  // 关闭传感器数据弹窗
  closeModal(): void {
    this.selectedCattle = null;
  }
}
