// PC/frontend/src/app/components/sensor-chart-modal/sensor-chart-modal.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Sensor } from '../../models/sensor';
import { Chart, ChartConfiguration, registerables } from 'chart.js';

// Register all Chart.js components
Chart.register(...registerables);

@Component({
  selector: 'app-sensor-chart-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './sensor-chart-modal.component.html',
  styleUrl: './sensor-chart-modal.component.scss'
})
export class SensorChartModalComponent implements OnInit, OnChanges {
  @Input() data!: Sensor;
  @Output() close = new EventEmitter<void>();
  
  private temperatureChart: Chart | null = null;
  private peristalticChart: Chart | null = null;

  ngOnInit(): void {
    this.initializeCharts();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['data'] && !changes['data'].firstChange) {
      this.updateCharts();
    }
  }

  onClose(): void {
    this.close.emit();
  }

  private initializeCharts(): void {
    // 确保可以获取到DOM元素
    setTimeout(() => {
      this.initializeTemperatureChart();
      this.initializePeristalticChart();
    }, 0);
  }

  private initializeTemperatureChart(): void {
    const ctx = document.getElementById('temperatureChart') as HTMLCanvasElement;
    if (!ctx) return;

    const formattedLabels = this.data.timestamps.map(
      timestamp => new Date(timestamp).toLocaleTimeString()
    );

    // 创建温度图表配置
    const config: ChartConfiguration<'line'> = {
      type: 'line',
      data: {
        labels: formattedLabels,
        datasets: [
          {
            label: '胃温度 (°C)',
            data: this.data.stomachTemperatures,
            borderColor: '#ff6384',
            backgroundColor: 'rgba(255, 99, 132, 0.1)',
            borderWidth: 2,
            pointRadius: 3,
            tension: 0.4,
            fill: true,
          }
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: true,
            position: 'top'
          }
        },
        scales: {
          x: {
            grid: {
              display: false
            }
          },
          y: {
            title: {
              display: true,
              text: '温度 (°C)'
            },
            ticks: {
              precision: 1
            }
          }
        }
      }
    };

    this.temperatureChart = new Chart(ctx, config);
  }

  private initializePeristalticChart(): void {
    const ctx = document.getElementById('peristalticChart') as HTMLCanvasElement;
    if (!ctx) return;

    const formattedLabels = this.data.timestamps.map(
      timestamp => new Date(timestamp).toLocaleTimeString()
    );

    // 创建蠕动图表配置
    const config: ChartConfiguration<'line'> = {
      type: 'line',
      data: {
        labels: formattedLabels,
        datasets: [
          {
            label: '蠕动次数 (次/分钟)',
            data: this.data.peristalticCounts,
            borderColor: '#36a2eb',
            backgroundColor: 'rgba(54, 162, 235, 0.1)',
            borderWidth: 2,
            pointRadius: 3,
            tension: 0.4,
            fill: true,
          }
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: true,
            position: 'top'
          }
        },
        scales: {
          x: {
            grid: {
              display: false
            }
          },
          y: {
            title: {
              display: true,
              text: '蠕动次数'
            },
            beginAtZero: true,
            ticks: {
              stepSize: 1,
              precision: 0
            }
          }
        }
      }
    };

    this.peristalticChart = new Chart(ctx, config);
  }

  private updateCharts(): void {
    this.updateTemperatureChart();
    this.updatePeristalticChart();
  }

  private updateTemperatureChart(): void {
    if (!this.temperatureChart) {
      this.initializeTemperatureChart();
      return;
    }

    const formattedLabels = this.data.timestamps.map(
      timestamp => new Date(timestamp).toLocaleTimeString()
    );

    this.temperatureChart.data.labels = formattedLabels;
    if (this.temperatureChart.data.datasets && this.temperatureChart.data.datasets.length > 0) {
      this.temperatureChart.data.datasets[0].data = this.data.stomachTemperatures;
    }

    this.temperatureChart.update();
  }

  private updatePeristalticChart(): void {
    if (!this.peristalticChart) {
      this.initializePeristalticChart();
      return;
    }

    const formattedLabels = this.data.timestamps.map(
      timestamp => new Date(timestamp).toLocaleTimeString()
    );

    this.peristalticChart.data.labels = formattedLabels;
    if (this.peristalticChart.data.datasets && this.peristalticChart.data.datasets.length > 0) {
      this.peristalticChart.data.datasets[0].data = this.data.peristalticCounts;
    }

    this.peristalticChart.update();
  }
}

<div class="modal">
  <div class="modal-content">
    <button class="close-button" (click)="onClose()">×</button>
    <div class="chart-title">牛只 {{data.cattleId}} 传感器数据</div>
    <div class="charts-container">
      <div class="chart-wrapper">
        <div class="chart-subtitle">胃温度数据 (°C)</div>
        <div class="chart-container">
          <canvas id="temperatureChart"></canvas>
        </div>
      </div>
      <div class="chart-wrapper">
        <div class="chart-subtitle">胃蠕动次数 (次/分钟)</div>
        <div class="chart-container">
          <canvas id="peristalticChart"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>

// src/components/SensorChartModal.tsx
import React from 'react';
import { Chart, ChartOptions } from 'chart.js';
import { registerables } from 'chart.js';
import { Line } from 'react-chartjs-2';
import { CattleSensorData } from '../types/sensor';
Chart.register(...registerables);

interface Props {
  data: CattleSensorData;
  onClose: () => void;
}

/**
 * 传感器数据图表弹窗组件
 * @param data 传感器数据
 * @param onClose 关闭回调函数
 * @returns 图表弹窗JSX元素
 */
export const SensorChartModal: React.FC<Props> = ({ data, onClose }) => {
  const chartData = {
    labels: data.timestamps.map(timestamp => new Date(timestamp).toLocaleTimeString()),
    datasets: [
      {
        label: '胃温度 (°C)',
        data: data.stomachTemperatures,
        borderColor: '#ff6384',
        yAxisID: 'temperature',
        tension: 0.4,
        fill: false,
      },
      {
        label: '蠕动次数 (次/分钟)',
        data: data.peristalticCounts,
        borderColor: '#36a2eb',
        yAxisID: 'peristaltic',
        tension: 0.4,
        fill: false,
      }
    ]
  };

  const options: ChartOptions<'line'> = {
    responsive: true,
    plugins: {
      title: {
        display: true,
        text: `牛只 ${data.cattleId} 传感器数据`
      }
    },
    scales: {
      temperature: {
        type: 'linear',
        position: 'left',
        title: { display: true, text: '温度 (°C)' }
      },
      peristaltic: {
        type: 'linear',
        position: 'right',
        title: { display: true, text: '蠕动次数' },
        grid: { display: false }
      }
    }
  };

  return (
    <div style={{
      position: 'fixed',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      backgroundColor: 'rgba(255, 255, 255, 0.95)',
      padding: '20px',
      borderRadius: '8px',
      boxShadow: '0 2px 10px rgba(0,0,0,0.2)',
      zIndex: 1001,
      minWidth: '600px'
    }}>
      <button 
        onClick={onClose}
        style={{
          position: 'absolute',
          right: '10px',
          top: '10px',
          background: 'none',
          border: 'none',
          cursor: 'pointer'
        }}
      >
        ×
      </button>
      <Line data={chartData} options={options} />
    </div>
  );
};
