// src/components/StatsPanel.tsx
import React from 'react';

interface HealthStats {
  healthy: number;
  warning: number;
  critical: number;
}

interface Props {
  cattleData: any[];
}

/**
 * 健康统计面板组件
 * @param cattleData 牲畜数据数组
 * @returns 统计面板JSX元素
 */
export const StatsPanel: React.FC<Props> = ({ cattleData }) => {
  // 计算健康状态分布
  const calculateStats = (): HealthStats => {
    const total = cattleData.length;
    const counts = cattleData.reduce((acc, curr) => {
      acc[curr.healthStatus] = (acc[curr.healthStatus] || 0) + 1;
      return acc;
    }, { healthy: 0, warning: 0, critical: 0 });

    return {
      healthy: Math.round((counts.healthy / total) * 100),
      warning: Math.round((counts.warning / total) * 100),
      critical: Math.round((counts.critical / total) * 100)
    };
  };

  const stats = calculateStats();

  return (
    <div style={{
      position: 'fixed',
      right: '20px',
      top: '20px',
      backgroundColor: 'rgba(255, 255, 255, 0.9)',
      padding: '20px',
      borderRadius: '8px',
      boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
      zIndex: 1000
    }}>
      <h3 style={{ marginTop: 0 }}>健康状态统计</h3>
      <div>健康：{stats.healthy}%</div>
      <div>警告：{stats.warning}%</div>
      <div>严重：{stats.critical}%</div>
    </div>
  );
};

// PC/frontend/src/app/components/stats-panel/stats-panel.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Cattle } from '../../models/cattle';

interface HealthStats {
  healthy: number;
  warning: number;
  critical: number;
}

@Component({
  selector: 'app-stats-panel',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './stats-panel.component.html',
  styleUrl: './stats-panel.component.scss'
})
export class StatsPanelComponent {
  @Input() cattleData: Cattle[] = [];
  
  // 计算健康状态分布百分比
  calculateStats(): HealthStats {
    const total = this.cattleData.length;
    if (total === 0) {
      return { healthy: 0, warning: 0, critical: 0 };
    }
    
    const counts = this.cattleData.reduce((acc, curr) => {
      const status = curr.healthStatus as keyof HealthStats;
      acc[status] = (acc[status] || 0) + 1;
      return acc;
    }, { healthy: 0, warning: 0, critical: 0 } as HealthStats);

    return {
      healthy: Math.round((counts.healthy / total) * 100),
      warning: Math.round((counts.warning / total) * 100),
      critical: Math.round((counts.critical / total) * 100)
    };
  }
}

<div class="stats-panel">
  <h3>牛群健康统计</h3>
  @if (cattleData.length > 0) {
    <div class="stat-item">
      <div class="stat-label">健康：</div>
      <div class="stat-value">{{ calculateStats().healthy }}%</div>
      <div class="stat-bar">
        <div class="stat-bar-fill healthy" [style.width.%]="calculateStats().healthy"></div>
      </div>
    </div>
    <div class="stat-item">
      <div class="stat-label">警告：</div>
      <div class="stat-value">{{ calculateStats().warning }}%</div>
      <div class="stat-bar">
        <div class="stat-bar-fill warning" [style.width.%]="calculateStats().warning"></div>
      </div>
    </div>
    <div class="stat-item">
      <div class="stat-label">严重：</div>
      <div class="stat-value">{{ calculateStats().critical }}%</div>
      <div class="stat-bar">
        <div class="stat-bar-fill critical" [style.width.%]="calculateStats().critical"></div>
      </div>
    </div>
  } @else {
    <div class="no-data">暂无数据</div>
  }
</div>
